'use server';
import { randomUUID } from 'crypto';import { redirect } from 'next/navigation';import { requireAdmin } from '@/lib/supabaseServer';import { getSupabaseAdmin } from '@/lib/supabaseAdmin';
function clean(v){return String(v||'').trim()} function money(v){return Math.round((Number(v||0)+Number.EPSILON)*100)/100}
export async function createOrder(formData){const {allowed,user}=await requireAdmin();if(!user||!allowed)redirect('/login');const admin=getSupabaseAdmin();const customerName=clean(formData.get('customer_name'));const facebookName=clean(formData.get('facebook_name'));const messengerPsid=clean(formData.get('messenger_psid'));const itemName=clean(formData.get('item_name'));const notes=clean(formData.get('notes'));const total=money(formData.get('total'));const token=randomUUID().replaceAll('-','');let photoUrl=clean(formData.get('photo_url'));
 let customerId=null;if(customerName||facebookName||messengerPsid){const {data:existing}=await admin.from('customers').select('*').or(`facebook_name.eq.${facebookName || '___'},messenger_psid.eq.${messengerPsid || '___'}`).limit(1).maybeSingle();if(existing){customerId=existing.id;await admin.from('customers').update({customer_name:customerName||existing.customer_name,facebook_name:facebookName||existing.facebook_name,messenger_psid:messengerPsid||existing.messenger_psid}).eq('id',customerId)}else{const {data:c,error}=await admin.from('customers').insert({customer_name:customerName,facebook_name:facebookName,messenger_psid:messengerPsid}).select().single();if(error)throw error;customerId=c.id}}
 const file=formData.get('photo');if(file&&file.size>0){const ext=(file.name?.split('.').pop()||'jpg').toLowerCase();const path=`orders/${token}.${ext}`;const buf=Buffer.from(await file.arrayBuffer());const {error:upErr}=await admin.storage.from('order-photos').upload(path,buf,{contentType:file.type||'image/jpeg',upsert:true});if(upErr)throw upErr;const {data:pub}=admin.storage.from('order-photos').getPublicUrl(path);photoUrl=pub.publicUrl}
 const {data:order,error}=await admin.from('orders').insert({customer_id:customerId,customer_name:customerName,facebook_name:facebookName,messenger_psid:messengerPsid,item_name:itemName,notes,total,photo_url:photoUrl,token,status:'pending_payment',created_by:user.email}).select().single();if(error)throw error;
 if(messengerPsid){const site=process.env.NEXT_PUBLIC_SITE_URL||'';try{await fetch(`${site}/api/messenger/send-order`,{method:'POST',headers:{'Content-Type':'application/json','x-internal-key':process.env.SUPABASE_SERVICE_ROLE_KEY||''},body:JSON.stringify({orderId:order.id})})}catch(e){}}
 redirect(`/admin/orders?created=${order.id}`)}
